#!/usr/bin/env python3
"""
Count Chinese-institution first-author papers for PLDI 2025, OOPSLA 2024, FSE 2025.
Data scraped directly from conference websites.
Chinese institution = mainland China / Hong Kong / Macau / Taiwan university,
research institute, or company.
"""

# Keywords indicating a Chinese institution
CN_KEYWORDS = [
    # Mainland China
    "china", "chinese", "beijing", "shanghai", "tsinghua", "peking", "pku",
    "fudan", "zhejiang", "nanjing", "sjtu", "shanghai jiao tong",
    "wuhan", "harbin", "sun yat-sen", "sysu", "xjtu", "xi'an jiaotong",
    "huawei", "alibaba", "tencent", "bytedance", "baidu", "didi",
    "chinese academy", "cas ", " cas,", "ict, cas", "ict cas",
    "iscas", "institute of software", "institute of computing technology",
    "national university of defense", "nudt",
    "university of science and technology of china", "ustc",
    "nankai", "tianjin", "chongqing", "sichuan", "tongji",
    "beihang", "buaa", "southeast university",
    "shenzhen", "guangzhou", "hangzhou",
    # Hong Kong
    "hong kong", "hkust", "hku ", "hku,", "cuhk", "cityu", "polyu",
    "chinese university of hong kong",
    # Taiwan
    "taiwan", "ntu.edu.tw", "academia sinica",
    # Macau
    "macau", "macao",
]

def is_cn_institution(affil: str) -> bool:
    if not affil:
        return False
    a = affil.lower()
    return any(kw in a for kw in CN_KEYWORDS)


# ── PLDI 2025 (from pldi25.sigplan.org) ──────────────────────────────────────
PLDI_2025 = [
    ("A Concurrent Approach to String Transformation Synthesis", "Yuantian Ding", "Purdue University"),
    ("Active Learning of Symbolic NetKAT Automata", "Mark Moeller", "Cornell University"),
    ("A Hybrid Approach to Semi-automated Rust Verification", "Sacha-Élie Ayoun", "Imperial College London"),
    ("An Interactive Debugger for Rust Trait Errors", "Gavin Gray", "Brown University"),
    ("A Uniform Framework for Handling Position Constraints in String Solving", "Yu-Fang Chen", "Academia Sinica"),
    ("Automated Exploit Generation for Node.js Packages", "Filipe Marques", "INESC-ID; Instituto Superior Técnico"),
    ("AWDIT: An Optimal Weak Database Isolation Tester", "Lasse Møldrup", "Aarhus University"),
    ("Bean: A Language for Backward Error Analysis", "Ariel E. Kellison", "Cornell University"),
    ("Certified Compilers à la Carte", "Oghenevwogaga Ebresafe", "University of Waterloo"),
    ("Circuit Optimization using Arithmetic Table Lookups", "Raghav Malik", "Purdue University"),
    ("CompCertOC: Verified Compositional Compilation", "Ling Zhang", "Shanghai Jiao Tong University"),
    ("Correctly Rounded Math Libraries", "Sehyeok Park", "Rutgers University"),
    ("CRGC: Fault-Recovering Actor Garbage Collection in Pekko", "Dan Plyukhin", "University of Southern Denmark"),
    ("Destabilizing Iris", "Simon Spies", "Jane Street"),
    ("Divergence-Aware Testing of Graphics Shader Compiler", "Dongwei Xiao", "Hong Kong University of Science"),
    ("DR.FIX: Automatically Fixing Data Races at Industry Scale", "Farnaz Behrang", "Uber Technologies"),
    ("Dynamic Region Ownership for Concurrency Safety", "Fridtjof Stoldt", "Uppsala University"),
    ("Dynamic Robustness Verification against Weak Memory", "Roy Margalit", "Tel Aviv University"),
    ("Efficient Formal Verification of Quantum Error Correcting Programs", "Qifan Huang", "Institute of Software at CAS"),
    ("Efficient Linearizability Monitoring", "Parosh Aziz Abdulla", "Uppsala University"),
    ("Efficient, Portable, Census-Polymorphic Choreographic Programming", "Mako P. Bates", "University of Vermont"),
    ("Efficient Timestamping for Sampling-Based Race Detection", "Minjian Zhang", "University of Illinois"),
    ("Exact Loop Bound Analysis", "Daniel Riley", "Florida State University"),
    ("Exploiting Undefined Behavior in C/C++ Programs", "Lucian Popescu", "INESC-ID; Instituto Superior Técnico"),
    ("Fast Direct Manipulation Programming", "Parker Ziegler", "UC Berkeley"),
    ("First-Class Verification Dialects for MLIR", "Mathieu Fehr", "University of Edinburgh"),
    ("Functional Meaning for Parallel Streaming", "Nick Rioux", "University of Pennsylvania"),
    ("Graphiti: Bridging Graph and Relational Database Queries", "Yang He", "Simon Fraser University"),
    ("Guided Tensor Lifting", "Yixuan Li", "University of Edinburgh"),
    ("Handling the Selection Monad", "Gordon Plotkin", "Google DeepMind"),
    ("Intrinsic Verification of Parsers and Formal Grammar Theory", "Steven Schaefer", "University of Michigan"),
    ("Iso: Request-Private Garbage Collection", "Tianle Qiu", "Australian National University"),
    ("Leveraging Immutability to Validate Hazard Pointers", "Janggun Lee", "KAIST"),
    ("LiDO-DAG: A Framework for Verifying Safety and Liveness", "Longfei Qiu", "Yale University"),
    ("Lightweight and Locality-Aware Composition of Black-Box Subroutines", "Manya Bansal", "MIT"),
    ("Link-Time Optimization of Dynamic Casts in C++", "Xufan Lu", "INESC-ID / Instituto Superior Técnico"),
    ("Making Concurrent Hardware Verification Sequential", "Thomas Bourgeat", "EPFL"),
    ("MarQSim: Reconciling Determinism and Randomness", "Xiuqi Cao", "University of Pennsylvania"),
    ("Membership Testing for Semantic Regular Expressions", "Yifei Huang", "University of Southern California"),
    ("MISAAL: Synthesis-Based Automatic Generation", "Abdul Rafae Noor", "University of Illinois"),
    ("Modular Construction and Optimization of the UZP Sparse Format", "Alonso Rodríguez-Iglesias", "Universidade da Coruña"),
    ("Morello-Cerise: A Proof of Strong Encapsulation", "Angus Hammond", "University of Cambridge"),
    ("Multi-stage Relational Programming", "Michael Ballantyne", "Northeastern University"),
    ("Nola: Later-Free Ghost State for Verifying Termination", "Yusuke Matsushita", "Kyoto University"),
    ("Optimization-Directed Compiler Fuzzing", "Jaeseong Kwon", "KAIST"),
    ("Optimizing Ancilla-Based Quantum Circuits with SPARE", "Ritvik Sharma", "Stanford University"),
    ("Partial Evaluation, Whole-Program Compilation", "Chris Fallin", "F5"),
    ("Pointer Analysis for Database-Backed Applications", "Yufei Liang", "Nanjing University"),
    ("Polygon: Symbolic Reasoning for SQL", "Pinhan Zhao", "University of Michigan"),
    ("Principal Type Inference under a Prefix", "Daan Leijen", "Microsoft Research"),
    ("Probabilistic Kleene Algebra with Angelic Nondeterminism", "Shawn Ong", "Cornell University"),
    ("Probabilistic Refinement Session Types", "Qiancheng Fu", "Boston University"),
    ("Program Skeletons for Automated Program Translation", "Bo Wang", "National University of Singapore"),
    ("Program Synthesis From Partial Traces", "Margarida Ferreira", "Carnegie Mellon University"),
    ("Programming by Navigation", "Justin Lubin", "UC Berkeley"),
    ("PulseCore: An Impredicative Concurrent Separation Logic", "Gabriel Ebner", "Microsoft Research"),
    ("QVM: Quantum Gate Virtualization Machine", "Nathaniel Tornow", "TU Munich"),
    ("Quantum Register Machine", "Zhicheng Zhang", "University of Technology Sydney"),
    ("Random Variate Generation with Formal Guarantees", "Feras Saad", "Carnegie Mellon University"),
    ("Relaxing Alias Analysis: Exploring the Unexplored Space", "Michel Weber", "ETH Zurich"),
    ("Relational Abstractions Based on Labeled Union-Find", "Dorian Lesbre", "Université Paris-Saclay - CEA LIST"),
    ("RefinedProsa: Connecting Response-Time Analysis", "Kimaya Bedarkar", "MPI-SWS"),
    ("Reductive Analysis with Compiler-Guided Language Models", "Xiangwei Wang", "North Carolina State University"),
    ("RippleAsynchronous Programming for Spatial Dataflow", "Souradip Ghosh", "Carnegie Mellon University"),
    ("Robust Constant-Time Cryptography", "Matthew Kolosick", "UC San Diego"),
    ("Robustifying Debug Information Updates in LLVM", "Shan Huang", "East China Normal University"),
    ("Roulette: A Language for Expressive, Exact, and Efficient", "Cameron Moy", "Northeastern University"),
    ("RRR-SMR: Reduce, Reuse, Recycle", "Md Amit Hasan Arovi", "Pennsylvania State University"),
    ("Scalable, Validated Code Translation of Entire Projects", "Hanliang Zhang", "University of Bristol"),
    ("Semantics of Integrating and Differentiating Singularities", "Jesse Michel", "MIT"),
    ("Slotted E-Graphs: First-Class Support for Variables", "Rudi Schneider", "Technische Universität Berlin"),
    ("Smooth, Integrated Proofs of Cryptographic Constant Time", "Owen Conoly", "MIT"),
    ("Solving Floating-Point Constraints", "Qian Chen", "Nanjing University"),
    ("Spineless Traversal for Layout Invalidation", "Marisa Kirisame", "University of Utah"),
    ("StacKAT: Infinite State Network Verification", "Jules Jacobs", "Cornell University"),
    ("Stochastic Lazy Knowledge Compilation for Inference", "Maddy Bowers", "MIT"),
    ("Support Triangle Machine", "Jiaying Li", "R3 Lab"),
    ("Taking out the Toxic Trash", "Fabian Stemmler", "TU Munich"),
    ("Task-Based Tensor Computations on Modern GPUs", "Rohan Yadav", "Stanford University"),
    ("Thrust: A Prophecy-Based Refinement Type System", "Hiromi Ogawa", "University of Tsukuba"),
    ("Tree Borrows", "Neven Villani", "University of Grenoble Alpes"),
    ("Type-Constrained Code Generation with Language Models", "Niels Mündler", "ETH Zurich"),
    ("Usability Barriers for Liquid Types", "Catarina Gamboa", "Carnegie Mellon University"),
    ("Verifying General-Purpose RCU for Reclamation", "Jaehwang Jung", "Rebellions Inc"),
    ("Verifying Lock-Free Traversals in Relaxed Memory", "Sunho Park", "KAIST"),
    ("Verifying Solutions to Semantics-Guided Synthesis", "Charlie Murphy", "Amazon Web Services"),
    ("Verified Foundations for Differential Privacy", "Markus de Medeiros", "New York University"),
    ("Webs and Flow-Directed Well-Typedness Preserving", "Benjamin Quiring", "University of Maryland"),
]

# ── OOPSLA 2024 (from 2024.splashcon.org) ────────────────────────────────────
OOPSLA_2024 = [
    ("Cocoon: Static Information Flow Control in Rust", "Ada Lamba", "Ohio State University"),
    ("Computing Precise Control Interface Specifications", "Eric Campbell", "Cornell University"),
    ("FlowCert: Translation Validation for Asynchronous Dataflow Programs", "Zhengyao Lin", "Carnegie Mellon University"),
    ("ParDiff: Practical Static Differential Analysis of Network Protocol Parsers", "Mingwei Zheng", "Purdue University"),
    ("Sound and partially-complete static analysis of data-races in GPU programs", "Dennis Liew", "University of Massachusetts Boston"),
    ("Law and Order for Typestate with Borrowing", "Hannes Saffrich", "University of Freiburg"),
    ("Taypsi: Static Enforcement of Privacy Policies", "Qianchuan Ye", "University at Buffalo, SUNY"),
    ("Gradient: Gradual Compartmentalization via Object Capabilities", "Aleksander Boruch-Gruszecki", "Charles University"),
    ("Automatically Reducing Privilege for Access Control Policies", "Loris D'Antoni", "University of Wisconsin-Madison"),
    ("Functional Ownership through Fractional Uniqueness", "Danielle Marshall", "University of Glasgow"),
    ("A Pure Demand Operational Semantics", "Scott F. Smith", "Johns Hopkins University"),
    ("Automating Pruning in Top-Down Enumeration", "Keith J.C. Johnson", "University of Wisconsin-Madison"),
    ("HOL4P4: mechanized small-step semantics for P4", "Anoud Alshnakat", "KTH Royal Institute of Technology"),
    ("Semantics Lifting for Syntactic Sugar", "Zhichao Guan", "Peking University"),
    ("Synthesizing Formal Semantics from Executable Interpreters", "Jiangyi Liu", "University of Wisconsin-Madison"),
    ("HardTaint: Production-Run Dynamic Taint Analysis", "Yiyu Zhang", "Nanjing University"),
    ("MEA2: a Lightweight Field-Sensitive Escape Analysis", "Boyao Ding", "University of Science and Technology of China"),
    ("Newtonian Program Analysis of Probabilistic Programs", "Di Wang", "Peking University"),
    ("Non-Termination Proving at Scale", "Azalea Raad", "Imperial College London"),
    ("Quantum Control Machine", "Charles Yuan", "Massachusetts Institute of Technology"),
    ("Accurate Data Race Prediction in the Linux Kernel", "Gabriel Ryan", "Columbia University"),
    ("Mix Testing: Specifying and Testing ABI Compatibility", "Luke Geeson", "University College London"),
    ("Practical Verification Of Smart Contracts Using Memory Splitting", "Shelly Grossman", "Tel Aviv University"),
    ("Fast and Optimal Extraction for Sparse Equality Graphs", "Amir Kafshdar Goharshady", "Hong Kong University of Science and Technology"),
    ("HybridSA: GPU Acceleration of Multi-Pattern Regex Matching", "Alexis Le Glaunec", "Rice University"),
    ("Realistic Realizability: Specifying ABIs You Can Count On", "Andrew Wagner", "Northeastern University"),
    ("AUTOMAP: Inferring Rank-Polymorphic Function Applications", "Robert Schenck", "DIKU, University of Copenhagen"),
    ("Outcome Separation Logic", "Noam Zilberstein", "Cornell University"),
    ("VarLifter: Recovering Variables and Types from Bytecode", "Yichuan Li", "Nanjing University of Science and Technology"),
    ("Weighted Context-Free-Language Ordered Binary Decision Diagrams", "Meghana Aparna Sistla", "University of Texas at Austin"),
    ("Enhancing Static Analysis for Practical Bug Detection", "Haonan Li", "University of California at Riverside"),
    ("PP-CSA: Practical Privacy-Preserving Software Call Stack Analysis", "Zhaoyu Wang", "HKUST"),
    ("Semantic-Type-Guided Bug Finding", "Kelvin Qian", "Johns Hopkins University"),
    ("Seneca: Taint-Based Call Graph Construction for Java Object Deserialization", "Joanna C. S. Santos", "University of Notre Dame"),
    ("VeriEQL: Bounded Equivalence Verification for Complex SQL Queries", "Yang He", "Simon Fraser University"),
    ("Jmvx: Fast Multi-threaded Multi-Version eXecution", "David Schwartz", "University of Illinois at Chicago"),
    ("libLISA: Instruction Discovery and Analysis on x86-64", "Jos Craaijo", "Open Universiteit"),
    ("Extending the C/C++ Memory Model with Inline Assembly", "Paulo Emílio de Vilhena", "Imperial College London"),
    ("TorchQL: A Programming Framework for Integrity Constraints", "Aaditya Naik", "University of Pennsylvania"),
    ("Verification of Neural Networks' Global Robustness", "Anan Kabaha", "Technion, Israel Institute of Technology"),
    ("A Constraint Solving Approach to Parikh Images of Regular Languages", "Amanda Stjerna", "Uppsala university"),
    ("Imperative Compositional Programming", "Wenjia Ye", "National University of Singapore"),
    ("Inductive diagrams for causal reasoning", "Jonathan Castello", "University of California, Santa Cruz"),
    ("Message-Observing Sessions", "Ryan Kavanagh", "Université du Québec à Montréal (UQAM)"),
    ("Plume: Efficient and Complete Black-box Checking of Weak Isolation Levels", "Si Liu", "ETH Zurich"),
    ("AdoB: Bridging Benign and Byzantine Consensus", "Wolf Honore", "Yale University"),
    ("Dependency-aware Code Naturalness", "Chen Yang", "Tianjin University"),
    ("Iterative-Epoch Online Cycle Elimination for CFL Reachability", "Pei Xu", "University of Technology Sydney"),
    ("Wasm-R3: Record-Reduce-Replay for Realistic WebAssembly Benchmarks", "Doehyun Baek", "KAIST"),
    ("When Your Infrastructure is a Buggy Program", "Georgios-Petros Drosos", "ETH Zurich"),
    ("A Typed Multi-Level Datalog IR and its Compiler Framework", "David Klopp", "JGU Mainz"),
    ("Finding Cross-rule Optimization Bugs in Datalog Engines", "Chi Zhang", "Nanjing University"),
    ("Making Formulog Fast", "Aaron Bembenek", "University of Melbourne"),
    ("Object-Oriented Fixpoint Programming with Datalog", "David Klopp", "JGU Mainz"),
    ("Scaling Abstraction Refinement for Program Analyses in Datalog", "Zhenyu Yan", "Peking University"),
    ("Compilation of Shape Operators on Sparse Arrays", "Alexander J Root", "Stanford University"),
    ("Compiler Support for Sparse Tensor Convolutions", "Peiming Liu", "Google Inc"),
    ("Compiling Recurrences over Dense and Sparse Arrays", "Shiv Sundram", "Stanford University"),
    ("Fully Verified Instruction Scheduling", "Ziteng Yang", "Georgia Institute of Technology"),
    ("Homeostasis: Design and Implementation of a Self-Stabilizing Compiler", "Aman Nougrahiya", "IIT Madras"),
    ("CYCLE: Learning to Self-Refine the Code Generation", "Yangruibo Ding", "Columbia University"),
    ("Evaluating the effectiveness of Deep Learning Models", "Qian Chen", "Nanjing University"),
    ("Knowledge Transfer from High-Resource to Low-Resource Programming Languages", "Federico Cassano", "Northeastern University"),
    ("Statically Contextualizing Large Language Models with Typed Holes", "Andrew Blinn", "University of Michigan"),
    ("WhiteFox: White-box Compiler Fuzzing Empowered by LLMs", "Chenyuan Yang", "University of Illinois at Urbana-Champaign"),
    ("Control-Flow Deobfuscation using Trace-Informed Synthesis", "Benjamin Mariano", "University of Texas at Austin"),
    ("Finding ∀∃ Hyperbugs Using Symbolic Execution", "Arthur Correnson", "CISPA Helmholtz Center for Information Security"),
    ("Mechanizing the CMP Abstraction for Parameterized Verification", "Yongjian Li", "Institute of Software, Chinese Academy of Sciences"),
    ("Model Checking Distributed Protocols in Must", "Constantin Enea", "LIX, CNRS, Ecole Polytechnique"),
    ("Monotone Procedure Summarization via Vector Addition Systems", "Nikhil Pimpalkhare", "Princeton University"),
    ("Hydra: Generalizing Peephole Optimizations with Program Synthesis", "Manasij Mukherjee", "NVIDIA"),
    ("Minotaur: A SIMD-Oriented Synthesizing Superoptimizer", "Zhengyang Liu", "University of Utah"),
    ("PolyJuice: Detecting Mis-Compilation Bugs in Tensor Compilers", "Chijin Zhou", "Tsinghua University"),
    ("SparseAuto: An Auto-Scheduler for Sparse Tensor Computations", "Adhitha Dias", "Purdue University"),
    ("Understanding and Finding Java Decompiler Bugs", "Yifei Lu", "Nanjing University"),
    ("Concurrent Data Structures Made Easy", "Callista Le", "Yale-NUS College"),
    ("Automated Verification of Parametric Channel-Based Process Communication", "Georgian-Vlad Saioc", "Aarhus University"),
    ("Automated Robustness Verification of Concurrent Data Structures", "Kartik Nagar", "IIT Madras"),
    ("Verified Lock-Free Session Channels with Linking", "Thomas Somers", "Radboud University Nijmegen"),
    ("Scenario-based Proofs for Concurrent Objects", "Constantin Enea", "LIX, CNRS, Ecole Polytechnique"),
    ("Intensional Functions", "Zachary Palmer", "Swarthmore College"),
    ("Qualifying System F-sub", "Edward Lee", "University of Waterloo"),
    ("Refinement Type Refutations", "Robin Webbers", "Vrije Universiteit Amsterdam"),
    ("Type Inference Logics", "Denis Carnier", "KU Leuven"),
    ("Polymorphic Reachability Types", "Guannan Wei", "Inria/ENS; Tufts University"),
    ("A modal type-theory of expected cost", "Vineet Rajani", "University of Kent"),
    ("Distributions for Compositionally Differentiating Parametric Discontinuities", "Jesse Michel", "Massachusetts Institute of Technology"),
    ("Exact Bayesian Inference for Loopy Probabilistic Programs", "Lutz Klinkenberg", "RWTH Aachen University"),
    ("Hopping Proofs of Expectation-Based Properties", "Martin Avanzini", "Inria"),
    ("Learning Abstraction Selection for Bayesian Program Analysis", "Yifan Zhang", "Peking University"),
    ("Modular Synthesis of Efficient Quantum Uncomputation", "Hristo Venev", "INSAIT, Sofia University"),
    ("Quantum Probabilistic Model Checking for Time-Bounded Properties", "Seungmin Jeon", "KAIST"),
    ("Quarl: A Learning-Based Quantum Circuit Optimizer", "Zikun Li", "Carnegie Mellon University"),
    ("Synthetiq: Fast and Versatile Quantum Circuit Synthesis", "Anouk Paradis", "ETH Zurich"),
    ("A Learning-Based Approach to Static Program Slicing", "Aashish Yadavally", "University of Texas at Dallas"),
    ("Boosting Alias-Aware IFDS Analysis with CFL-based Environment Transformers", "Haofeng Li", "Institute of Computing Technology at Chinese Academy of Sciences"),
    ("The ART of Sharing Points-to Analysis", "Shashin Halalingaiah", "UT Austin, IIT Madras"),
    ("UniSparse: An Intermediate Language for General Sparse Format Customization", "Jie Liu", "Cornell University"),
    ("Programmable MCMC with Soundly Composed Guide Programs", "Long Pham", "Carnegie Mellon University"),
    ("Quantitative Bounds on Resource Usage of Probabilistic Programs", "Krishnendu Chatterjee", "IST Austria"),
    ("Sensitivity by Parametricity", "Elisabet Lobo-Vesga", "DPella AB"),
    ("Tachis: Higher-Order Separation Logic with Credits for Expected Costs", "Philipp G. Haselwarter", "Aarhus University"),
    ("A Dependent Nominal Physical Type System for Static Analysis of Memory", "Julien Simonnet", "CEA LIST"),
    ("Modeling Dynamic (De)Allocations of Local Memory for Translation Validation", "Abhishek Rose", "IIT Delhi"),
    ("Mark-Scavenge: Waiting for Trash to Take Itself Out", "Jonas Norlinder", "Uppsala University"),
    ("Iris-MSWasm: elucidating the security invariants of Memory-Safe WebAssembly", "Maxime Legoupil", "Aarhus University"),
    ("Cedar: A New Language for Expressive, Fast, Safe, and Analyzable Authorization", "Joseph W. Cutler", "University of Pennsylvania"),
    ("CoolerSpace: A Language for Physically Correct and Computationally Efficient Color Programming", "Ethan Chen", "University of Rochester"),
    ("Design and Implementation of an Aspect-Oriented C Programming Language", "Zhe Chen", "Nanjing University of Aeronautics and Astronautics"),
    ("On the Expressive Power of Languages for Static Variability", "Paul Maximilian Bittner", "Paderborn University"),
    ("QuAC: Quick Attribute-Centric Type Inference for Python", "Jifeng Wu", "University of British Columbia"),
    ("A Case for First-Class Environments", "Jinhao Tan", "University of Hong Kong"),
    ("Deriving Dependently-Typed OOP from First Principles", "David Binder", "University of Tübingen"),
    ("Multiverse Notebook: Shifting Data Scientists to Time Travelers", "Shigeyuki Sato", "University of Electro-Communications"),
    ("The Ultimate Conditional Syntax", "Luyu Cheng", "Hong Kong University of Science and Technology"),
    ("Unifying Static and Dynamic Intermediate Languages for Accelerator Generators", "Caleb Kim", "MIT"),
]

# ── FSE 2025 (from conf.researchr.org) ───────────────────────────────────────
FSE_2025 = [
    ("Incorporating Verification Standards for Security Requirements Generation", "Xiaoli Lian", "Beihang University, China"),
    ("Unlocking Optimal ORM Database Designs", "Md Rashedul Hasan", "University of Nebraska-Lincoln"),
    ("The Struggles of LLMs in Cross-lingual Code Clone Detection", "Micheline Bénédicte MOUMOULA", "University of Luxembourg"),
    ("Clone Detection for Smart Contracts: How Far Are We?", "Zuobin Wang", "Zhejiang University"),
    ("An Empirical Study of Code Clones from Commercial AI Code Generators", "Weibin Wu", "Sun Yat-sen University"),
    ("VulPA: Detecting Semantically Recurring Vulnerabilities", "Liqing Cao", "Institute of Computing Technology at Chinese Academy of Sciences"),
    ("Mystique: Automated Vulnerability Patch Porting", "Susheng Wu", "Fudan University"),
    ("Code Change Intention, Development Artifact and History Vulnerability", "Xu Yang", "University of Manitoba"),
    ("Teaching AI the 'Why' and 'How' of Software Vulnerability Fixes", "Amiao Gao", "Southern Methodist University"),
    ("CoverUp: Effective High Coverage Test Generation for Python", "Juan Altmayer Pizzorno", "University of Massachusetts Amherst"),
    ("Doc2OracLL: Investigating the Impact of Documentation", "Soneya Binta Hossain", "University of Virginia"),
    ("Less is More: On the Importance of Data Quality for Unit Test Generation", "Junwei Zhang", "Zhejiang University"),
    ("On-Demand Scenario Generation for Testing Automated Driving Systems", "Songyang Yan", "Xi'an Jiaotong University"),
    ("Multi-Modal Traffic Scenario Generation for Autonomous Driving System Testing", "Zhi Tu", "Purdue University"),
    ("A Comprehensive Study of Bug-Fix Patterns in Autonomous Driving Systems", "Yuntianyi Chen", "University of California, Irvine"),
    ("Understanding Debugging as Episodes", "Max Weber", "Leipzig University"),
    ("Towards Understanding Performance Bugs in Popular Data Science Libraries", "Haowen Yang", "The Chinese University of Hong Kong, Shenzhen"),
    ("COFFE: A Code Efficiency Benchmark for Code Generation", "Yun Peng", "The Chinese University of Hong Kong"),
    ("No More Labelled Examples? An Unsupervised Log Parser with LLMs", "Junjie Huang", "The Chinese University of Hong Kong"),
    ("Protecting Privacy in Software Logs", "Roozbeh Aghili", "Polytechnique Montréal"),
    ("10 years later: revisiting how developers search for code", "Kathryn Stolee", "North Carolina State University"),
    ("Zero-Shot Cross-Domain Code Search without Fine-Tuning", "Keyu Liang", "Zhejiang University"),
    ("MiSum: Multi-Modality Heterogeneous Code Graph Learning", "Kangchen Zhu", "National University of Defense Technology"),
    ("Dynamic Taint Tracking for Modern Java Virtual Machines", "Katherine Hough", "Northeastern University"),
    ("An Empirical Study of Suppressed Static Analysis Warnings", "Huimin Hu", "University of Stuttgart"),
    ("A New Approach to Evaluating Nullability Inference Tools", "Nima Karimipour", "University of California, Riverside"),
    ("Liberating libraries through automated fuzz driver generation", "Flavio Toffalini", "EPFL, Switzerland"),
    ("MendelFuzz: The Return of the Deterministic Stage", "Han Zheng", "EPFL"),
    ("A Knowledge Enhanced Large Language Model for Bug Localization", "Yue Li", "Nanjing University"),
    ("Dissecting Real-World Cross-Language Bugs", "Haoran Yang", "Washington State University"),
    ("Towards Understanding Fine-Grained Programming Mistakes in Data Science", "Weihao Chen", "Purdue University"),
    ("Error Delayed is Not Error Handled", "Haoran Liu", "National University of Defense Technology"),
    ("Accuracy Can Lie: On the Impact of Surrogate Model in Configuration Tuning", "Pengzhou Chen", "University of Electronic Science and Technology of China"),
    ("Exploring the Effectiveness of LLMs in Automated Logging Statement Generation", "Yichen Li", "The Chinese University of Hong Kong"),
    ("Approaching Code Search for Python as a Translation Retrieval Problem", "Monoshiz Mahbub Khan", "Rochester Institute of Technology"),
    ("Automated Soap Opera Testing Directed by LLMs", "Yanqi Su", "Australian National University"),
    ("Automated Test Case Repair Using Language Models", "Ahmadreza Saboor Yaraghi", "University of Ottawa"),
    ("TestGPT-Server: Automatically Testing Microservices with LLMs at ByteDance", "Jue Wang", "ByteDance"),
    ("LTM: Scalable and Black-Box Similarity-Based Test Suite Minimization", "Rongqi Pan", "University of Ottawa"),
    ("Yuga: Automatically Detecting Lifetime Annotation Bugs in Rust", "Vikram Nitin", "Columbia University"),
    ("dl²: Detecting Communication Deadlocks in Deep Learning Jobs", "Yanjie Gao", "Microsoft Research"),
    ("Detecting Metadata-Related Bugs in Enterprise Applications", "Md Mahir Asef Kabir", "Virginia Tech"),
    ("ROSCallBaX: Statically Detecting Inconsistencies in Callback Function Setup", "Sayali Kate", "Purdue University"),
    ("Enhancing Web Accessibility: Automated Detection of Issues with Generative AI", "Ziyao He", "University of California, Irvine"),
]


def analyze(name: str, papers: list[tuple]) -> dict:
    total = len(papers)
    cn_papers = [(t, a, inst) for t, a, inst in papers if is_cn_institution(inst)]
    cn_count = len(cn_papers)
    pct = round(cn_count / max(total, 1) * 100, 1)
    print(f"\n{'='*70}")
    print(f"{name}: {total} papers, {cn_count} CN institution first-author ({pct}%)")
    print(f"{'─'*70}")
    for t, a, inst in cn_papers:
        print(f"  ✓ {a:30s}  {inst}")
    return {"name": name, "total": total, "cn": cn_count, "pct": pct}


if __name__ == "__main__":
    results = []
    results.append(analyze("PLDI 2025", PLDI_2025))
    results.append(analyze("OOPSLA 2024", OOPSLA_2024))
    results.append(analyze("FSE 2025", FSE_2025))

    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'─'*70}")
    for r in results:
        print(f"{r['name']:15}  total={r['total']:4d}  CN={r['cn']:3d}  ({r['pct']:.1f}%)")
